version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: gitlab-timetracking-dashboard:latest
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
