version: "3.8"

services:
  app:
    image: ghcr.io/di0ik/gitlab-timetracking-analysis:main
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
